"use client";

import { useEffect, useState } from "react";
type Policy = { auditDays: number; aiDetailDays: number; completedJobDays: number; webhookDeliveryDays: number };
export function RetentionPanel() {
  const [policy, setPolicy] = useState<Policy>({ auditDays: 365, aiDetailDays: 90, completedJobDays: 30, webhookDeliveryDays: 30 }); const [preview, setPreview] = useState<Record<string, number> | null>(null); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void fetch("/api/v1/retention-policy").then((response) => response.json()).then((body) => { if (body.policy) setPolicy(body.policy); }); }, []);
  const update = (key: keyof Policy, value: string) => setPolicy({ ...policy, [key]: Math.max(1, Math.min(3650, Number(value) || 1)) });
  async function save() { const response = await fetch("/api/v1/retention-policy", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(policy) }); const body = await response.json(); setMessage(response.ok ? "Retention policy saved and audited." : body.error ?? "Unable to save policy"); }
  async function loadPreview() { const response = await fetch("/api/v1/retention-policy/preview"); const body = await response.json(); if (response.ok) setPreview(body.preview ?? body); }
  return <div className="grid gap-5 lg:grid-cols-[1fr_0.8fr]"><section className="card p-5"><h2 className="text-sm font-semibold text-slate-950">Retention windows</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{([ ["auditDays", "Audit events"], ["aiDetailDays", "AI detail"], ["completedJobDays", "Completed jobs"], ["webhookDeliveryDays", "Webhook deliveries"] ] as Array<[keyof Policy, string]>).map(([key, label]) => <label key={key} className="label">{label}<div className="mt-1 flex items-center gap-2"><input type="number" min={1} max={3650} className="input" value={policy[key]} onChange={(event) => update(key, event.target.value)} /><span className="text-xs text-slate-500">days</span></div></label>)}</div><div className="mt-5 flex flex-wrap gap-2"><button type="button" className="btn-primary" onClick={() => void save()}>Save policy</button><button type="button" className="btn-secondary" onClick={() => void loadPreview()}>Preview deletion</button></div>{message && <p className="mt-3 text-sm text-slate-600" role="status">{message}</p>}</section><section className="card p-5"><h2 className="text-sm font-semibold text-slate-950">Preview</h2>{preview ? <dl className="mt-4 space-y-3">{Object.entries(preview).map(([key, value]) => <div key={key} className="flex items-center justify-between gap-3 text-sm"><dt className="text-slate-600">{key}</dt><dd className="font-semibold text-slate-950">{value}</dd></div>)}</dl> : <p className="mt-3 text-sm leading-6 text-slate-600">A preview uses the current policy and reports bounded counts before deletion.</p>}</section></div>;
}
